"use client";
import { useStore } from "@/providers/StoreProvider";
import { ScreenSkeleton } from "@/components/ui/ScreenSkeleton";
import { PageHeader } from "@/components/layout/PageHeader";
import { Section, Metrics, durationLabel } from "@/components/learning/StudyControls";
import { accuracy, needsAttention, studyAnalytics } from "@/lib/learning/analytics";
import { getDueCards } from "@/lib/learning/scheduling";
import { studyUrl } from "@/lib/learning/content";
import { StarButton } from "@/components/learning/StarButton";
export function ProgressView() {
  const { ready, decks, history, events } = useStore();
  if (!ready) return <ScreenSkeleton />;
  const cards = decks.flatMap(deck => deck.cards), stats = studyAnalytics(events, history);
  const max = Math.max(1, ...stats.days.map(day => day.count));
  const difficult = cards.filter(card => needsAttention(card));
  const modes = { flashcards: "Flashcards", learn: "Learn", match: "Match", test: "Test", review: "Daily Review" };
  return <div className="space-y-8"><PageHeader eyebrow="Progress" title="Your learning, over time" description="Real study activity, saved on this device." />
    <Section title="Today"><Metrics values={[["Cards studied", stats.cards], ["Questions answered", stats.questions], ["Minutes studied", Math.floor(stats.durationMs / 60000)], ["Accuracy", accuracy(stats.correct, stats.incorrect)], ["Cards mastered", stats.mastered], ["Current streak", `${stats.streak} days`], ["Longest streak", `${stats.longest} days`]]} /></Section>
    <Section title="Last 7 days"><p className="text-sm text-muted">Questions and card reviews per day.</p><div className="flex items-end gap-3" role="img" aria-label={stats.days.map(day => `${day.date}: ${day.count} answers`).join("; ")}>{stats.days.map(day => <div key={day.date} className="flex min-w-0 flex-1 flex-col items-center gap-2"><span className="text-sm tabular-nums">{day.count}</span><div className="flex h-28 w-full items-end rounded-lg bg-surface-2"><div className="w-full rounded-lg bg-accent" style={{ height: `${day.count / max * 100}%` }} /></div><span className="text-xs text-muted">{new Date(day.date + "T12:00:00").toLocaleDateString(undefined, { weekday: "short" })}</span></div>)}</div></Section>
    <Section title="Mastery"><Metrics values={(["New", "Learning", "Familiar", "Mastered"] as const).map(level => [level, cards.filter(card => card.masteryLevel === level).length])} /></Section>
    <Section title="Needs Attention">{!difficult.length ? <p className="text-muted">No difficult material yet. Missed answers and overdue reviews will appear here.</p> : <ul className="divide-y divide-edge">{decks.filter(deck => difficult.some(card => card.deckId === deck.id)).map(deck => <li key={deck.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="font-medium">{deck.title}</p><p className="text-sm text-muted">{difficult.filter(card => card.deckId === deck.id).length} cards need attention</p></div><a className="study-link" href={studyUrl(deck.id, "learn", difficult.filter(card => card.deckId === deck.id).map(card => card.id))}>Review difficult cards</a></li>)}</ul>}</Section>
    <Section title="Starred"><Metrics values={[["Starred terms", cards.filter(card => card.termStarred).length], ["Starred definitions", cards.filter(card => card.definitionStarred).length]]} /><div className="space-y-2">{decks.filter(deck => deck.cards.some(card => card.termStarred || card.definitionStarred)).map(deck => <div key={deck.id} className="flex flex-wrap items-center gap-3"><span className="mr-auto">{deck.title}</span><a className="study-link" href={studyUrl(deck.id, "flashcards", undefined, "terms")}>Study terms</a><a className="study-link" href={studyUrl(deck.id, "flashcards", undefined, "definitions")}>Study definitions</a></div>)}</div></Section>
    <Section title="Deck performance">{!decks.length ? <p className="text-muted">Create a deck to start tracking your progress.</p> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-edge">{["Deck", "Mastery", "Recent accuracy", "Due", "Study time"].map(label => <th key={label} className="px-2 py-3 font-medium">{label}</th>)}</tr></thead><tbody>{decks.map(deck => { const recent = history.filter(item => item.deckId === deck.id).sort((a, b) => b.startedAt - a.startedAt).slice(0, 10); const correct = recent.reduce((n, item) => n + item.correct, 0), incorrect = recent.reduce((n, item) => n + item.incorrect, 0); const deckEvents = events.filter(item => item.deckId === deck.id); return <tr key={deck.id} className="border-b border-edge"><td className="max-w-52 break-words px-2 py-4"><a className="underline" href={`/library/${deck.id}`}>{deck.title}</a></td><td className="px-2">{deck.cards.length ? `${Math.round(deck.cards.reduce((n, card) => n + card.mastery, 0) / deck.cards.length)}%` : "—"}</td><td className="px-2">{accuracy(correct, incorrect)}</td><td className="px-2">{getDueCards(deck.cards).length}</td><td className="px-2">{durationLabel(deckEvents.reduce((n, item) => n + item.durationMs, 0))}</td></tr>; })}</tbody></table></div>}</Section>
    <Section title="Recent sessions">{!history.length ? <p className="rounded-2xl border border-dashed border-edge p-6 text-muted">Your first session starts the story. Study a deck and return here to see what changed.</p> : <ul className="divide-y divide-edge">{history.slice().sort((a, b) => b.startedAt - a.startedAt).slice(0, 20).map(item => <li key={item.id} className="flex flex-wrap justify-between gap-3 py-4"><div><p className="font-medium">{item.title} · {modes[item.mode]}</p><p className="text-sm text-muted">{new Date(item.startedAt).toLocaleString()} · {item.endedAt ? "Completed" : "In progress"}</p></div><p className="text-sm text-muted">{item.correct + item.incorrect} answers · {accuracy(item.correct, item.incorrect)} · {durationLabel(item.durationMs)}</p></li>)}</ul>}</Section>
    {difficult.length > 0 && <Section title="Difficult terms"><ul className="divide-y divide-edge">{difficult.slice(0, 10).map(card => <li key={card.id} className="flex items-center justify-between py-3"><span className="break-words">{card.term}</span><StarButton card={card} side="term" /></li>)}</ul></Section>}
  </div>;
}
