"use client";
import type { ReactNode } from "react";
import { contentLabels, type ContentFilter, type Direction } from "@/lib/learning/content";
export const fieldClass = "mt-2 min-h-12 w-full rounded-xl border border-edge bg-surface px-3 py-2 text-base outline-none focus-visible:border-accent focus-visible:ring-2 focus-visible:ring-accent/20";
export function Section({ title, children }: { title: string; children: ReactNode }) { return <section className="space-y-4 border-t border-edge/80 pt-6"><h2 className="font-display text-xl tracking-tight">{title}</h2>{children}</section>; }
export function ContentSelect({ value, onChange }: { value: ContentFilter; onChange: (value: ContentFilter) => void }) { return <label className="block text-sm">Content<select className={fieldClass} value={value} onChange={e => onChange(e.target.value as ContentFilter)}>{Object.entries(contentLabels).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label>; }
export function DirectionSelect({ value, onChange }: { value: Direction; onChange: (value: Direction) => void }) { return <label className="block text-sm">Answer with<select className={fieldClass} value={value} onChange={e => onChange(e.target.value as Direction)}><option value="term">Definition (show term)</option><option value="definition">Term (show definition)</option><option value="mixed">Mixed directions</option></select></label>; }
export function Toggle({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) { return <label className="flex min-h-12 items-center gap-3 rounded-xl px-1 text-base"><input className="h-6 w-6 shrink-0 accent-accent" type="checkbox" checked={value} onChange={e => onChange(e.target.checked)} />{label}</label>; }
export function Metrics({ values }: { values: [string, string | number][] }) { return <dl className="grid grid-cols-2 gap-x-6 gap-y-5 sm:grid-cols-3">{values.map(([label, value]) => <div key={label}><dt className="text-sm text-muted">{label}</dt><dd className="mt-1 font-display text-2xl tabular-nums">{value}</dd></div>)}</dl>; }
export function durationLabel(ms: number) { return `${Math.floor(ms / 60000)}m ${Math.floor(ms / 1000) % 60}s`; }
